language: node_js

node_js:
  - "6"

services:
  - mongodb

script:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
